--------------------------------------------------------
--  File created - Thursday-March-27-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE" 
   (	"EMPLOYEEID" VARCHAR2(5 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"DEPARTMENTID" NUMBER, 
	"JOINEDDATE" DATE, 
	"GENDER" VARCHAR2(10 BYTE), 
	"SALARY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLOYEE
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYEE (EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENTID,JOINEDDATE,GENDER,SALARY) values ('E1','Sehath','Nethsara',1001,to_date('05-APR-20','DD-MON-RR'),'Male',25500);
Insert into SYSTEM.EMPLOYEE (EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENTID,JOINEDDATE,GENDER,SALARY) values ('E2','Avin','Malaka',1002,to_date('21-MAR-21','DD-MON-RR'),'Male',47000);
Insert into SYSTEM.EMPLOYEE (EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENTID,JOINEDDATE,GENDER,SALARY) values ('E3','Maneesha','Devmi',1003,to_date('10-MAY-22','DD-MON-RR'),'Female',40000);
Insert into SYSTEM.EMPLOYEE (EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENTID,JOINEDDATE,GENDER,SALARY) values ('E4','Sathish','Perera',1001,to_date('25-AUG-22','DD-MON-RR'),'Male',45000);
Insert into SYSTEM.EMPLOYEE (EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENTID,JOINEDDATE,GENDER,SALARY) values ('E5','Kalani','Madushika',1003,to_date('02-MAY-23','DD-MON-RR'),'Female',51000);
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLE1_PK" ON "SYSTEM"."EMPLOYEE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "SYSTEM"."DEPARTMENT" ("DEPARTMENTID") ENABLE;
